---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "freemium-hosting.fullname" . }}-env
  labels:
    {{- include "freemium-hosting.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.application.port | quote }}