---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "freemium-hosting.fullname" . }}-env
  labels:
    {{- include "freemium-hosting.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.application.port | quote }}
  DB_URL: {{ printf "jdbc:h2:file://%s/%s" .Values.db.persistence.mountPath .Values.db.name | quote }}

