apiVersion: v1
kind: Service
metadata:
  name: {{ include "freemium-hosting.fullname" . }}
  labels:
    {{- include "freemium-hosting.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.port }}
      port: {{ .Values.application.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "freemium-hosting.selectorLabels" . | nindent 4 }}
