server:
  port: ${PORT:8080}

spring:
  h2:
    console:
      enabled: true
  mvc:
    static-path-pattern: /**
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    username: ${DB_USERNAME:user}
    password: ${DB_PASS:12345}
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
freemium:
  hosting:
    git-clone-path: ${GIT_CLONE_TEMP_PATH:./tmp/git-clone}
    default-builder-path:  ${GIT_CLONE_TEMP_PATH:./tmp/builder}
    dockerfile:
      builder-image: ${JAVA_BUILDER_IMAGE:maven:3.6.3-jdk-14} #TODO: change version
      workdir: ${DOCKER_BUILD_WORKDIE:/usr/src/app/backend}
      build-command: ${JAVA_BUILD_COMMAND:mvn install -DskipTests=true}
      java-image: ${JAVA_RUN_IMAGE:openjdk:14-jdk} #TODO: change to jre
