name: Build and Deploy to K8s

on:
  push:
    branches: [ "ci" ] #TODO: change to main

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  IMAGE_NAME: freemium-hosting
  REGISTRY_LOGIN: freemiumhosting
  REGISTRY_PASSWORD: freemiumhosting
  DEPLOYMENT_NAME: iks-test
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  KUBE_CONFIG_PATH: /opt/app/kubeconfig.yml
  HELM_IMAGE: alpine/helm
  HELM_VERSION: 3.7.1
  BUILD_PATH: /opt/build

#  PORT: 5001

jobs:
  build-jar:
    name: Build jar
    runs-on: ubuntu-latest
    environment: production
    container:
      image: maven:3.6.3-openjdk-11-slim
      volumes:
        - build:$BUILD_PATH
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build jar
        run: mvn -DskipTests=true clean install
      - name: Copy artifact
        run: cp ./target/*.jar $BUILD_PATH/app.jar

  build-docker:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      # Build the Docker image
      - name: Build with Docker
        run: docker build -t "$IMAGE_NAME":"$GITHUB_SHA" --build-arg GITHUB_SHA="$GITHUB_SHA" $BUILD_PATH
      # Push the image to Registry
      - name: Push the image to Registry
        run: docker push $IMAGE_NAME:$GITHUB_SHA

#  deploy-to-cluster:
#    name: Deploy to cluster
#    runs-on: ubuntu-latest
#    container:
#      image: ${HELM_IMAGE}:${HELM_VERSION}
#    steps:
#      - name: Write kubeconfig
#        run: |
#          echo "${KUBE_CONFIG}" > ${KUBE_CONFIG_PATH}
#          chmod 600 ${KUBE_CONFIG_PATH}
#
#        # Deploy the Docker image to the cluster
#      - name: Deploy to K8S   #TODO: check vars
#        run: |
#          export DEPLOYS=$(helm ls -n ${NAMESPACE} --kubeconfig ${KUBE_CONFIG_PATH} | awk '{print $1}' | grep -E -- "^$APP$" | wc -l)
#          export HELM_KEYS="${APP} ./.helm/charts/${APP}
#                --set image.name=${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${APP}
#                --set image.tag=${VERSION}
#                --set commitId=${CI_COMMIT_SHORT_SHA}
#                -f $HELM_VALUES_DIR/common.yaml
#                -f $HELM_VALUES_DIR/${APP}.yaml
#                -f $HELM_VALUES_DIR/replicas/${APP}.yaml
#                -n ${NAMESPACE}
#                --kubeconfig ${KUBE_CONFIG_PATH}"
#          if [ ${DEPLOYS}  -eq 0 ];
#                then helm install $HELM_KEYS;
#                else helm upgrade $HELM_KEYS;
#          fi

